config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
  	resources :replies
  end

  root 'posts#index'
   
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :replies
end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :posts
  has_many :replies
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]
	before_action :find_post, only: [:show, :edit, :update, :destroy]

	def index
		@posts = Post.all.order("created_at DESC")
	end
	
	def show
		@post= Post.find(params[:id])
	end

	def new
		@post = current_user.posts.build
	end

	def create
		@post = current_user.posts.build(post_params)

		if @post.save
			redirect_to root_path
			else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @post.update(post_params) 
			redirect_to post_path
		else
			render "edit"
		end
	end

	def destroy
		@post.destroy
		redirect_to root_path
	end

	private

	def post_params
		params.require(:post).permit(:title, :description)
	end

	def find_post
		@post = Post.find(params[:id])
	end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
	before_action :authenticate_user!
	before_action :find_post, only: [:create, :edit, :update, :delete]
	before_action :find_reply, only: [:edit, :update, :delete]

	def create
		@reply = @post.replies.create(reply_params)
		@reply.user_id = current_user.id

		if @reply.save
				redirect_to post_path(@post)
			else
				render 'new'
		end
	end

	def edit
	end

  def show
    @reply=Reply.find(params[:id])
  end

	def update
		if @reply.update(reply_params)
			redirect_to post_path(@post)
		else
			render "edit"
		end
	end

	def delete
		@reply.destroy
		redirect_to post_path(@post)
	end


	private

	def reply_params
		params.require(:reply).permit(:content)
	end	

	def find_post
		@post = Post.find(params[:post_id])
	end

	def find_reply
		@reply = @post.replies.find(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TTSForum</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-default">
		<div class = "container">
			<div class = "navbar-header">
				<%= link_to "TTS Forum", root_path, class: "navbar-brand" %>
			</div>

			<ul class="navebar-nav nav navbar-right">
				<% if user_signed_in? %>
						<li><%=link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
					<% else %>
						<li><%=link_to "Log In", new_user_session_path %></li>
						<li><%=link_to "Sign Up", new_user_registration_path %></li>

				<%end%>
			</ul>

			<% if user_signed_in? %>
				<p><%= link_to "New Post", new_post_path, class: "navbar-text navbar-link" %></p>
				<%end%>
		</div>
	</nav>	

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div class = "container">
<%= yield %>
</div>

</body>
</html>

app/views/posts/_form.html.erb
 <%= simple_form_for @post do |f| %>
  <%= f.input :title, label: "Title"%>
  <%= f.input :description, label: "Comments "%>
  <%= f.button :submit %>
<% end %>

app/views/posts/edit.html.erb
 <div class="col-md-8 col-md-offset-2">
 <h1 class = "new-post-header">Edit Post</h1>
 <%= render "form" %>
 </div>

app/views/posts/new.html.erb
 <div class="col-md-8 col-md-offset-2">
 <h2 class = "new-post-header">New Post</h2>
 <%= render "form" %>
 </div>

app/views/posts/show.html.erb
<div class ="col-md-10 col-md-offset-1">
	<div class="post-show">
		<h3><%=@post.title%></h3>
			<p class="post-posted-by"><%= time_ago_in_words(@post.created_at) %> ago </p>
			<p class="post-desc"><%= @post.description %></p>
			<br>

			<h4 class='reply-section-header'>Replies</h4>
			<p><%= render @post.replies %></p>

<!--			<h3 class ='reply-to-post'>Reply</h3>  -->
			<%= render 'replies/form' %>


		<div class="links btn-group">
		<br>
			<%= link_to "Back", root_path, class: "btn btn-default" %>

			<% if user_signed_in? %>
			<% if @post.user_id == current_user.id%>

			<%= link_to "Edit", edit_post_path(@post), class: "btn btn-primary" %>
			<%= link_to "Delete", post_path(@post), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger" %>
			<%end%>
			<%end%>
		</div>

	</div>
</div>

app/views/replies/_form.html.erb
 <%= simple_form_for ([@post, @post.replies.build]) do |f| %>
  <%= f.input :content, label: "Reply below:"%>
  <%= f.button :submit, :class => 'btn-custom' %>
<% end %>

app/views/replies/_reply.html.erb
<div class = "reply">
	<p class ="reply-content"><%= reply.content %></p>
	<p class = "reply-posted-by"> By: <%=reply.user.email %> <%= time_ago_in_words(reply.created_at) %> ago </p>

	<div class="links">
		<% if user_signed_in? %>
		 	<% if reply.user_id == current_user.id %>	  
				<%= link_to "Edit", edit_post_reply_path(reply.post, reply) %>
				<%= link_to "Delete", post_reply_path(reply.post, reply), mothod: :delete , data: { confirm: "Are you sure?"} %> 
		 	<%end%>
		<%end%>	
	</div>
</div>

app/views/replies/edit.html.erb
<<h1>Edit Comment</h1>
<%= simple_form_for ([@post, @post.replies.build]) do |f| %>
  <%= f.input :content, label: "Reply below:"%>
  <%= f.button :submit, :class => 'btn-custom' %>
<% end %>